version: '3.2'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_DEV=dev
      - PORT=4000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
